import { pgEnum } from "drizzle-orm/pg-core";

export const accountTypeEnum = pgEnum("account_type", [
  "asset",
  "cash",
  "wallet",
  "credit_card",
  "liability",
  "investment",
]);

export const transactionTypeEnum = pgEnum("transaction_type", [
  "income",
  "expense",
  "transfer",
  "adjustment",
  "opening_balance",
]);

/**
 * Lifecycle of a transaction:
 * - pending:  draft generated by a recurring template, awaiting review
 * - imported: created from an import, awaiting review
 * - reviewed: human-confirmed but not yet considered final
 * - posted:   final ledger entry (manual entries start here)
 * - rejected: excluded from the ledger, kept for audit/provenance
 */
export const transactionStatusEnum = pgEnum("transaction_status", [
  "pending",
  "imported",
  "reviewed",
  "posted",
  "rejected",
]);

export const importFileStatusEnum = pgEnum("import_file_status", [
  "uploaded",
  "mapped",
  "previewed",
  "committed",
  "failed",
]);

export const importRowStatusEnum = pgEnum("import_row_status", [
  "pending",
  "approved",
  "rejected",
  "duplicate",
  "error",
]);

export const recurrenceIntervalEnum = pgEnum("recurrence_interval", [
  "weekly",
  "monthly",
  "quarterly",
  "yearly",
]);

/**
 * PRD §9.10, scoped down: a fixed bill projects at its typed amount with
 * high confidence; a variable one prefers the amount of the transaction that
 * last actually paid it — real history beats a manually typed guess — and
 * only falls back to the typed amount when no such history exists yet.
 */
export const amountStrategyEnum = pgEnum("amount_strategy", ["fixed", "variable"]);

export const ruleConditionFieldEnum = pgEnum("rule_condition_field", [
  "description_contains",
  "amount_equals",
  "amount_greater_than",
  "amount_less_than",
  "account_is",
  "raw_text_contains",
  "transaction_type_is",
]);

export const ruleActionTypeEnum = pgEnum("rule_action_type", [
  "set_category",
  "add_tag",
  "rename_merchant",
  "mark_reviewed",
  "assign_budget",
  "link_bill",
]);

export const ruleRunTriggerEnum = pgEnum("rule_run_trigger", [
  "manual",
  "import",
  "test",
]);
